---
apiVersion: v1
kind: Service
metadata:
  name: todo-api
  labels:
    app: todos-backend
spec:
  selector:
    app: todos-backend
  ports:
    - protocol: TCP
      port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-backend
  labels:
    app: todos-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todos-backend
  template:
    metadata:
      labels:
        app: todos-backend
    spec:
      containers:
        - name: todos-backend
          imagePullPolicy: IfNotPresent
          image: todos-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: TODO_USER
              value: "tester"
            - name: TODO_PASS
              value: "testerpassword"
            - name: TODO_DBNAME
              value: "testing_db"
            - name: TODO_DB_HOST
              value: todo-db
          livenessProbe:
            httpGet:
              port: 8080
              path: /healthz
            initialDelaySeconds: 3
            periodSeconds: 3