---
apiVersion: v1
kind: Service
metadata:
  name: todo-db
spec:
  ports:
    - port: 5432
      name: postgres
  clusterIP: None
  selector:
    app: todo-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  labels:
    app: todo-db
spec:
  selector:
    matchLabels:
      app: todo-db
  serviceName: "todo-db"
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - image: postgres:13.1-alpine
          name: postgres
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pg-data
          envFrom:
            - configMapRef:
                name: todos-db-postgres
  volumeClaimTemplates:
    - metadata:
        name: pg-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: db
        resources:
          requests:
            storage: 1Gi
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: db
provisioner: k8s.io/minikube-hostpath
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: todos-db-postgres
  labels:
    app: postgres
data:
  POSTGRES_USER: "tester"
  POSTGRES_DB: "testing_db"
  POSTGRES_PASSWORD: "testerpassword"